### ISSUE TITLE
Update changelog and upgrade guide

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#512]
@ralphtheninja should we:

1. Only link to the `abstract-leveldown` upgrade guide
2. Copy relevant parts (seeking, rejecting nullish values, serialization of range options, ..)

I'm leaning towards 2, because a large chunk of the `abstract-leveldown` upgrade guide is about tests.

Also, is there anything else you want to include in the new `leveldown` major?

**Comment by ralphtheninja** [comment]
> I'm leaning towards 2, because a large chunk of the `abstract-leveldown` upgrade guide is about tests.

Sounds good to me.



> Also, is there anything else you want to include in the new `leveldown` major?

Not that I can think of. Good work!

**Comment by vweevers** [comment]
Picking some low hanging fruit:

- [ ] #499 (to complete the serialization story)
- [ ] https://github.com/Level/abstract-leveldown/pull/300#issuecomment-431597600 (to restore a segfault test removed in `abstract-leveldown@6`)
- [ ] #134 (easy to fix and also about segfaults)
- [ ] #507 (to make sure we didn't introduce bugs)
- [ ] #496 (to complete the refactored chained batch story)

**Comment by vweevers** [comment]
For reference, I'm excluding the following items from the changelog:

-   Upgrade `nan` from `TODO` to `2.11.0` (#501)
-   Upgrade `prebuild-install` from `TODO` to `5.0.0` (#490)
-   Upgrade `prebuild` devDependency from `TODO` to `8.0.0` (#502)

As `nan` is gone and the `prebuild` things will be replaced by `prebuildify`.
