### ISSUE TITLE
Meta-issue to track cross-compiling progress

### ISSUE THREAD

**Issue by vweevers** [Level/leveldown#575]
As this effort spans multiple projects (both in tooling and target audience). In mostly chronological order:

- [x] [`prebuildify`](https://github.com/mafintosh/prebuildify)
  - [x] Allow overriding `strip` command (PR: https://github.com/mafintosh/prebuildify/pull/19)
  - [x] Allow overriding `platform` ~(mafintosh/prebuildify#22)~ (PR: mafintosh/prebuildify#26)
  - [x] Add libc flavor and arm version to prebuild name (PR: https://github.com/prebuild/prebuildify/pull/27)
- [x] [`node-gyp-build`](https://github.com/mafintosh/node-gyp-build)
   - [x] Support prebuilds for libc and arm flavors (PR: https://github.com/mafintosh/node-gyp-build/pull/14)
   - [x] Use new naming scheme (PR: https://github.com/prebuild/node-gyp-build/pull/19)
- [x] ~~[`prebuildify-cross`](https://github.com/ahdinosaur/prebuildify-cross): feature complete? TBD~~ using docker directly
- [x] [`docker-images`](https://github.com/prebuild/docker-images) (PR: https://github.com/prebuild/docker-images/pull/5)
- [x] [`leveldown`](https://github.com/Level/leveldown)
  - [x] Integrate `prebuildify-cross`: (PR: ~~https://github.com/Level/leveldown/pull/572~~ #584)
  - [x] Upgrade above deps (PR: https://github.com/Level/leveldown/pull/625)
     - [x] Add `--tag-armv` flag in `scripts/cross-compile` (this ensures that e.g. armv6 machines don't select the armv7 prebuild)
     - [x] Replace `npx prebuildify -t 8.14.0 --napi --strip` with `npm run prebuild` (now equal)
  - [x] Determine which ARM flavors we actually need (discussion: #574)
  - [x] Change Travis setup
    - [x] Add cross-compiling to matrix (PR: #585)
    - [x] Don't pass `-t electron@3.0.0` to `prebuildify` when cross-compiling

Feel free to edit if I missed anything.

cc @ralphtheninja @ahdinosaur @staltz @mafintosh

**Comment by ralphtheninja** [comment]
> How do we pass ARM version suffix for output folder (e.g. `-v7`) to `prebuildify`?

The `ARM_VERSION` environment variable is passed on the docker container here https://github.com/ahdinosaur/prebuildify-cross/blob/master/build#L237 , so it's available to `prebuildify` when invoked here https://github.com/ahdinosaur/prebuildify-cross/blob/master/build-in-docker#L16

So we need to modify `prebuildify` to create this suffix for the arm case here https://github.com/mafintosh/prebuildify/blob/master/index.js#L33

>  Same question for libc flavor. Or should `prebuildify` always include it in output folder names?

I guess this should go into `prebuildify` in the same sense. If you think about it, `prebuildify` is used to make the binaries and `node-gyp-build` tries to load them, so it makes sense that they have similar/mirrored behavior (i.e. producer/consumer logic)

**Comment by ahdinosaur** [comment]
> * Don't pass `-t electron@3.0.0` to `prebuildify` when cross-compiling

oh okay good to know. should i change the api of `prebuildify-cross` so that it takes arguments to pass to `prebuildify`? at the moment it just runs `npm run prebuild`, without any way to change arguments specifically for the prebuild.

i could change the `prebuildify-cross` api to something like:

```
prebuildify-cross --args="-t 8.14.0 --napi --strip" --platform=linux --arch=arm --arm-version=7
```

would that be helpful? if so, here's a branch for that functionality: https://github.com/ahdinosaur/prebuildify-cross/tree/prebuildify-args :star2: 

(by the way, i will be away from my computer for next 5 days, off to party in the bush :national_park:  :sunny: :dancer: :notes: )

**Comment by ralphtheninja** [comment]
> Don't pass `-t electron@3.0.0` to `prebuildify` when cross-compiling

@vweevers At first I was wondering why we shouldn't do this, but I guess it doesn't make any sense to do this for e.g. `android`, but maybe we want this for other flavors? Would it make sense to have prebuilts made for `electron` on say Raspberry PI?

> would that be helpful?

@ahdinosaur Yes, I think this would be helpful, since we need to have different behavior for `npm run prebuild` depending on which targets we are building for.

**Comment by vweevers** [comment]
**Status update:** it has taken quite a few iterations (of PRs, test releases and discussions), but I think we finally have a complete plan now. Note that some of the discussion above is outdated as we decided to replace `prebuildify-cross` with our ([prebuild](https://github.com/prebuild)'s) own Docker images.

I've opened https://github.com/prebuild/prebuildify/pull/26 which consolidates recent ad-hoc changes (for overriding strip, platform, arch) into a clean and documented set of options. Once that is merged, we'll have to update the Docker images accordingly. Then we can implement the new naming scheme for prebuilds (https://github.com/prebuild/prebuildify/issues/25), on which the discussion has now settled as well.

The only thing that's unclear to me is Android support. Specifically, whether to use and target the [`nodejs-mobile`](https://github.com/janeasystems/nodejs-mobile) forks of node and `node-gyp`. I'm not convinced that's the way to go, because I'm afraid we'll be stuck with it. Node core is open to improving Android support - so that's what I prefer to aim for. I don't see an easy way to support both.

**Comment by staltz** [comment]
@vweevers `nodejs-mobile` uses node chakracore because (for reasons I can't remember now but Janea systems documents it well) that makes it possible to run in iOS. Having leveldown supported in iOS is as important as Android support in my opinion. Node core isn't yet as developer friendly as nodejs-mobile is when targeting mobile.

**Comment by vweevers** [comment]
Would it be an option to use node core for Android, and `nodejs-mobile` for iOS? The former is already working. For the latter, I'm hoping that:

1. Telling `prebuildify` to use `nodejs-mobile-gyp` instead of `node-gyp` is enough to get prebuilds working, running in a MacOS job in Travis
2. `os.platform()` returns a distinct value (e.g. `ios`?) so that `node-gyp-build` can select the correct prebuild.

**Comment by vweevers** [comment]
> `nodejs-mobile` uses node chakracore because (for reasons I can't remember now [..]) that makes it possible to run in iOS

Thanks to [this tweet](https://twitter.com/v8js/status/1105777150051999744) I learned it's because iOS disallows write-access to executable memory. V8 7.4 addresses this by introducing a interpreter-only mode. Some time in the future node core should be able to take advantage of that!

cc @mcollina Does node have any official plans yet?
